// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Flags from "../lib/Flags.res.mjs";
import * as Helpers from "../lib/Helpers.res.mjs";

async function main(ns) {
  var match = Flags.getFlagsExn(ns, {
        help: false
      });
  var args = match[1];
  if (match[0].help) {
    ns.tprint("Tries to get root access on servers.\nArguments are servers' hostnames. If no arguments, tries to get root access on all servers.\n");
  } else if (args.length > 0) {
    args.forEach(function (s) {
          Helpers.getRootAccess(ns, s);
        });
  } else {
    Helpers.crawlServers(ns, undefined, undefined).forEach(function (s) {
          Helpers.getRootAccess(ns, s);
        });
  }
}

export {
  main ,
}
/* No side effect */
