// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Flags from "../lib/Flags.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

async function main(ns) {
  var match = Flags.getFlagsExn(ns, Flags.onlyHelpSchema);
  if (match[0].help) {
    ns.tprint("Weakens the server continuously.\nThe first argument should be the target server's hostname. If not specified, defaults to foodnstuff");
    return ;
  }
  var server = Core__Option.getOr(match[1][0], "foodnstuff");
  while(true) {
    await ns.weaken(server, undefined);
  };
}

function autocomplete(data, args) {
  var args$1 = Flags.argsToStrings(args);
  if (Flags.argsHasHelp(args$1)) {
    return [];
  } else {
    Flags.schemaToFlagsExn(data.flags, Flags.onlyHelpSchema);
    if (args$1.length <= 1) {
      return data.servers;
    } else {
      return [];
    }
  }
}

export {
  main ,
  autocomplete ,
}
/* No side effect */
