// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Flags from "../lib/Flags.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

async function main(ns) {
  var match = Flags.getFlagsExn(ns, Flags.onlyHelpSchema);
  if (match[0].help) {
    ns.tprint("Weakens the server continuously.\nThe first argument should be the target server's hostname.");
    return ;
  }
  var server = Core__Option.getOr(match[1][0], "foodnstuff");
  while(true) {
    await ns.weaken(server, undefined);
  };
}

function autocomplete(data, param) {
  var match = Flags.schemaToFlagsExn(data.flags, Flags.onlyHelpSchema);
  if (match[0].help) {
    return [];
  } else {
    return data.servers;
  }
}

export {
  main ,
  autocomplete ,
}
/* No side effect */
