// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Flags from "../lib/Flags.res.mjs";

async function main(ns) {
  var match = Flags.getFlagsExn(ns, {
        help: false
      });
  if (match[0].help) {
    ns.tprint("Weakens the server once.\nThe first argument should be the target server's hostname.");
    return ;
  }
  var server = match[1][0];
  if (server !== undefined) {
    await ns.weaken(server, undefined);
  } else {
    ns.tprint("The first argument is missing. It should be the target server's hostname.");
  }
}

export {
  main ,
}
/* No side effect */
