// Generated by ReScript, PLEASE EDIT WITH CARE


function crawlServers(ns, excludePurchasedServersOpt, excludeHomeOpt) {
  var excludePurchasedServers = excludePurchasedServersOpt !== undefined ? excludePurchasedServersOpt : false;
  var excludeHome = excludeHomeOpt !== undefined ? excludeHomeOpt : true;
  var servers = new Set();
  var getServers = function (_server, remains) {
    while(true) {
      var server = _server;
      if (servers.has(server)) {
        var s = remains.values().next().value;
        if (s === undefined) {
          return ;
        }
        remains.delete(s);
        _server = s;
        continue ;
      }
      servers.add(server);
      ns.scan(server).forEach(function (s) {
            remains.add(s);
          });
      continue ;
    };
  };
  getServers(ns.getHostname(), new Set());
  if (excludePurchasedServers) {
    ns.getPurchasedServers().forEach(function (s) {
          servers.delete(s);
        });
  }
  if (excludeHome) {
    servers.delete("home");
  }
  return servers;
}

export {
  crawlServers ,
}
/* No side effect */
