// Generated by ReScript, PLEASE EDIT WITH CARE

import * as PervasivesU from "rescript/lib/es6/pervasivesU.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function getFlagsExn(ns, obj) {
  var schema = Object.keys(obj).map(function (key) {
        var value = Core__Option.getExn(obj[key]);
        if (Array.isArray(value)) {
          value.forEach(function (v) {
                if (typeof v !== "string") {
                  return PervasivesU.invalid_arg("object's value is not a array of string");
                }
                
              });
          return [
                  key,
                  value
                ];
        }
        var match = typeof value;
        if (match === "boolean") {
          return [
                  key,
                  value
                ];
        } else if (match === "string") {
          return [
                  key,
                  value
                ];
        } else if (match === "number") {
          return [
                  key,
                  value
                ];
        } else {
          return PervasivesU.invalid_arg("object's value must be a string, float or bool");
        }
      });
  var flags = ns.flags(schema);
  return [
          flags,
          flags["_"]
        ];
}

export {
  getFlagsExn ,
}
/* No side effect */
