// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_math from "rescript/lib/es6/js_math.js";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";

function crawlServers(ns, excludePurchasedServersOpt, excludeHomeOpt) {
  var excludePurchasedServers = excludePurchasedServersOpt !== undefined ? excludePurchasedServersOpt : false;
  var excludeHome = excludeHomeOpt !== undefined ? excludeHomeOpt : true;
  var servers = new Set();
  var getServers = function (_server, remains) {
    while(true) {
      var server = _server;
      if (servers.has(server)) {
        var s = remains.values().next().value;
        if (s === undefined) {
          return ;
        }
        remains.delete(s);
        _server = s;
        continue ;
      }
      servers.add(server);
      ns.scan(server).forEach(function (s) {
            remains.add(s);
          });
      continue ;
    };
  };
  getServers(ns.getHostname(), new Set());
  if (excludePurchasedServers) {
    ns.getPurchasedServers().forEach(function (s) {
          servers.delete(s);
        });
  }
  if (excludeHome) {
    servers.delete("home");
  }
  return servers;
}

function getRootAccess(ns, host) {
  var info = ns.getServer(host);
  if (info.hasAdminRights) {
    return true;
  }
  var match = info.openPortCount;
  var match$1 = info.numOpenPortsRequired;
  if (match === undefined) {
    return false;
  }
  if (match$1 === undefined) {
    return false;
  }
  if (match < match$1) {
    if (!info.sshPortOpen && ns.fileExists("BruteSSH.exe", "home")) {
      ns.brutessh(host);
    }
    var info$1 = ns.getServer(host);
    if (info$1.openPortCount < info$1.numOpenPortsRequired && !info$1.ftpPortOpen && ns.fileExists("FTPCrack.exe", "home")) {
      ns.ftpcrack(host);
    }
    var info$2 = ns.getServer(host);
    if (info$2.openPortCount < info$2.numOpenPortsRequired && !info$2.smtpPortOpen && ns.fileExists("relaySMTP.exe", "home")) {
      ns.relaysmtp(host);
    }
    var info$3 = ns.getServer(host);
    if (info$3.openPortCount < info$3.numOpenPortsRequired && !info$3.httpPortOpen && ns.fileExists("HTTPWorm.exe", "home")) {
      ns.httpworm(host);
    }
    var info$4 = ns.getServer(host);
    if (info$4.openPortCount < info$4.numOpenPortsRequired && !info$4.sqlPortOpen && ns.fileExists("SQLInject.exe", "home")) {
      ns.sqlinject(host);
    }
    
  }
  var info$5 = ns.getServer(host);
  if (info$5.openPortCount < info$5.numOpenPortsRequired) {
    return false;
  }
  if (ns.fileExists("NUKE.exe", "home")) {
    ns.nuke(host);
    var info$6 = ns.getServer(host);
    if (info$6.hasAdminRights) {
      return true;
    } else {
      ns.print("ERROR: failed to get root access on server " + host);
      return false;
    }
  }
  ns.print("ERROR: no NUKE.exe on home server");
  return false;
}

function uploadFile(ns, server, file) {
  if (ns.fileExists(file, undefined)) {
    if (ns.scp(file, server, undefined)) {
      return true;
    } else {
      ns.print("ERROR: failed to upload file " + file + " to server " + server);
      return false;
    }
  } else {
    ns.print("ERROR: file " + file + " does not exist on current server " + ns.getHostname());
    return false;
  }
}

function execScript(ns, server, script, threads, uploadOpt, args) {
  var upload = uploadOpt !== undefined ? uploadOpt : true;
  var upload$1 = server === ns.getHostname() ? false : upload;
  var args$1 = Core__Option.getOr(args, []).map(function (arg) {
        return arg;
      });
  if (upload$1 && !uploadFile(ns, server, script)) {
    return {
            TAG: "Error",
            _0: "failedToUploadFile"
          };
  }
  var scriptRAM = ns.getScriptRam(script, server);
  if (scriptRAM <= 0.0) {
    return {
            TAG: "Error",
            _0: "fileNotExist"
          };
  }
  var exec = function (threads) {
    if (threads < 1) {
      return {
              TAG: "Error",
              _0: "invalidThreads"
            };
    }
    var pid = Caml_splice_call.spliceObjApply(ns, "exec", [
          script,
          server,
          threads,
          args$1
        ]);
    if (pid !== 0) {
      return {
              TAG: "Ok",
              _0: [
                pid,
                threads,
                scriptRAM * threads
              ]
            };
    } else {
      return {
              TAG: "Error",
              _0: "failedToExecScript"
            };
    }
  };
  if (threads !== undefined) {
    return exec(threads);
  }
  var ram = ns.getServerMaxRam(server) - ns.getServerUsedRam(server);
  if (ram > 0.0 && ram >= scriptRAM) {
    return exec(Js_math.floor_int(ram / scriptRAM));
  } else {
    return {
            TAG: "Error",
            _0: "noEnoughRAM"
          };
  }
}

export {
  crawlServers ,
  getRootAccess ,
  uploadFile ,
  execScript ,
}
/* No side effect */
