// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Helpers from "./Helpers.res.mjs";
import * as Js_math from "rescript/lib/es6/js_math.js";

function weakenThreads(ns, host) {
  var info = ns.getServer(host);
  var match = info.hackDifficulty;
  var match$1 = info.minDifficulty;
  if (match === undefined) {
    return {
            TAG: "Error",
            _0: "notHackableServer"
          };
  }
  if (match$1 === undefined) {
    return {
            TAG: "Error",
            _0: "notHackableServer"
          };
  }
  var toWeaken = match - match$1;
  if (toWeaken <= 0.0) {
    return {
            TAG: "Ok",
            _0: 0
          };
  }
  var singleWeaken = ns.weakenAnalyze(1, Helpers.getHomeCores(ns));
  return {
          TAG: "Ok",
          _0: Js_math.ceil_int(toWeaken / singleWeaken)
        };
}

export {
  weakenThreads ,
}
/* No side effect */
